### ISSUE TITLE
Simple implementation

### ISSUE THREAD

**Issue by pedroalbanese** [MJKWoolnough/dos2unix#1]
Greetings!

Sorry but what am I doing wrong? 

```go
		data, _ := ioutil.ReadAll(os.Stdin)
		reader := bytes.NewReader(data)
		fmt.Printf("%s\n", dos2unix.Unix2DOS(reader))
```

Thanks in advance.

**Comment by MJKWoolnough** [comment]
The Unix2Dos function returns an io.Reader, not a byte slice or string. Try something like the following:

`io.Copy(os.Stdout, dos2unix.Unix2DOS(os.Stdin))`

**Comment by pedroalbanese** [comment]
Thank You!
