### ISSUE TITLE
Failing case

### ISSUE THREAD

**Issue by AlexVasiluta** [MJKWoolnough/dos2unix#2]
Hello! I wanted to make use of your library and thought about doing some testing first. It seems that the byte sequence `\r\r\n` is outputted as is when passing it through your library, but the dos2unix CLI program (which I would interpret as a source of truth for the implementation) would convert it to `\r\n` (it could be argued that it's still windows format, but a CR was removed, so it is doing something at least).

Reproduction code:
```go
data, _ := io.ReadAll(dos2unix.DOS2Unix(strings.NewReader("Lorem\r\r\nIpsum")))
fmt.Printf("%q", data) // Prints "Lorem\r\r\nIpsum", expected "Lorem\r\nIpsum"
```

(by the way, I don't think your ByteReader wrapper is efficient performance-wise, since an io.Reader that does not buffer reads can incur many smaller fetches / syscalls. Probably a `bufio.Reader` would be better in this case, or at least a warning in the package documentation)

**Comment by MJKWoolnough** [comment]
Ah, good spot; I'll get on this today.

**Comment by MJKWoolnough** [comment]
…and done.

DOS2Unix should now correctly handle sequential '\r' bytes, and be more efficient with the Reader.

As per your suggestion, I also added a note to the Unix2DOS comment about using a buffered Reader.
